# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config

# See: https://circleci.com/docs/configuration-reference
 https://github.com/Maxwell-Lam/BMICalculator/blob/main/.circleci/config.yml
version: 2.1

orbs:
  python: circleci/python@2.1.1
  coveralls: coveralls/coveralls@2.2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      # Replace this with a real test runner invocation
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Build Pytest
          command: |
            pip install -r requirements.txt
            coverage run -m pytest test.py
            coverage report
            coveralls --repo-token=RE6TLjhyIVaXbapK0OAMllp8BwHOJJPOc
            #coverage run --source=my_package -m pytest tests.py  
            #COVERALLS_REPO_TOKEN="RE6TLjhyIVaXbapK0OAMllp8BwHOJJPOc" coveralls
      - run:
          name: Run tests
          command: python -m pytest tests.py && echo "Testing Starting Here"
workflows:
  example:
    jobs:
      - test
